name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Update to Node.js 20-compatible version
    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Update to Node.js 20-compatible version
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb  # Install tkinter and Xvfb
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Start Xvfb (Virtual Display)
      run: |
        Xvfb :99 &  # Start virtual display on :99
        export DISPLAY=:99  # Set display environment variable

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Python Scripts
      run: |
        python joes_generator_with_gui_pulled_enhancements.py  # Runs with GUI support
        python "Joes Gantt Generator No GUI_Simple.py"  # Add other scripts as needed

    - name: Test with pytest
      run: |
        pytest || echo "No tests found, skipping pytest step"
